# Change these first
owner: bang1338 # Your GitHub organization or username, where this repository lives
repo: iscsdown 2 # The name of this repository

sites:
  - name: Comic Studio
    url: https://comic.studio
  - name: Comic Studio CDN
    url: https://cdn.comic.studio
  - name: bang1338 (domain)
    url: https://bang1338.xyz
  - name: bang1338 (github)
    url: bang1338.github.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: iscsdown2.bang1338.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**iscsdown 2**"
  introMessage: just a status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
